import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Navbar } from "./components/nav";
import Footer from "./components/footer";
import { inter } from "./ui/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Carlo Ignacio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className='text-black bg-white dark:text-white dark:bg-black'
    >
      <body className={`antialiased max-w-3xl mx-2 mt-6 mx-auto ${inter.className}`}>
        <main className="flex-auto min-w-0 mt-4 flex flex-col px-0 md:px-0">
          <Navbar />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
